package initializers

import (
	"github.com/FuturaInsTech/GoLifeLib/models"
	"github.com/FuturaInsTech/GoLifeLib/models/quotation"
)

// Table Name should start with Capital Letter
func SyncDatabase() {
	// All Drop Down Come First
	DB.AutoMigrate(&models.Language{})
	// DB.AutoMigrate(&models.Currency{})
	// DB.AutoMigrate(&models.Gender{})
	// DB.AutoMigrate(&models.Salutation{})
	// DB.AutoMigrate(&models.UserStatus{})
	// DB.AutoMigrate(&models.UserGroup{})
	// DB.AutoMigrate(&models.ContHeader{})
	// DB.AutoMigrate(&models.CompanyStatus{})
	DB.AutoMigrate(&models.Company{})
	// DB.AutoMigrate(&models.Transaction{})
	// DB.AutoMigrate(&models.TDFRule{})
	// DB.AutoMigrate(&models.Permission{})
	// DB.AutoMigrate(models.LeadChannel{})
	DB.AutoMigrate(&models.User{})
	// DB.AutoMigrate(&models.Coverage{})
	// DB.AutoMigrate(&models.Load{})
	DB.AutoMigrate(&models.Client{})
	// DB.AutoMigrate(&models.ParamDesc{})
	// DB.AutoMigrate(&models.Param{})
	// DB.AutoMigrate(&models.Address{})
	// DB.AutoMigrate(&models.Relationship{})
	// DB.AutoMigrate(&models.Nominee{})
	// DB.AutoMigrate(&models.UinMaster{})
	// DB.AutoMigrate(&models.Error{})
	// DB.AutoMigrate(&models.Bank{})
	// DB.AutoMigrate(&models.Agency{})
	// DB.AutoMigrate(models.LeadDetail{})
	// DB.AutoMigrate(models.LeadFollowup{})
	// DB.AutoMigrate(&models.Quotation{})
	// DB.AutoMigrate(&models.LeadAllocation{})
	// DB.AutoMigrate(&models.Campaign{})
	// DB.AutoMigrate(&models.CampaignComp{})
	DB.AutoMigrate(&quotation.QHeader{})
	// DB.AutoMigrate(&quotation.QDetail{})
	// DB.AutoMigrate(&quotation.QBenIllValue{})
	// DB.AutoMigrate(&models.FieldValidator{})
	// DB.AutoMigrate(&models.Level{})
	DB.AutoMigrate(&models.Policy{})
	// DB.AutoMigrate(&models.Benefit{})
	// DB.AutoMigrate(&models.Extra{})
	// DB.AutoMigrate(&models.PHistory{})
	// DB.AutoMigrate(models.GlType{})
	// DB.AutoMigrate(models.AccountCode{})
	// DB.AutoMigrate(&models.GlMove{})
	// DB.AutoMigrate(&models.GlBal{})
	// DB.AutoMigrate(&models.Receipt{})
	DB.AutoMigrate(&models.Tdfh{})
	DB.AutoMigrate(&models.TDFPolicy{})
	//DB.AutoMigrate(&sudmodels.UIMaster{})
	DB.AutoMigrate(&models.TDFParam{})
	// DB.AutoMigrate(&models.SurvB{})
	// DB.AutoMigrate(&models.Communication{})
	// DB.AutoMigrate(&models.Uwreason{})
	// DB.AutoMigrate(&models.MedProvider{})
	// DB.AutoMigrate(&models.MedReq{})
	// DB.AutoMigrate(&models.Nominee{})
	// DB.AutoMigrate(&models.DeathH{})
	// DB.AutoMigrate(&models.DeathD{})
	// DB.AutoMigrate(&quotation.Qcommunication{})
	// DB.AutoMigrate(&models.Payer{})
	// DB.AutoMigrate(&models.SaChange{})
	// DB.AutoMigrate(&models.Assignee{})
	// DB.AutoMigrate((&models.Addcomponent{}))
	// DB.AutoMigrate(&models.Mrta{})
	// DB.AutoMigrate((&models.SurrH{}))
	// DB.AutoMigrate(&models.SurrD{})
	//DB.AutoMigrate(&models.BusinessDate{})

}
